import { LOCAL_AI_DEFAULT_MODEL_ID } from '@/common/contracts/local-ai';

export const SettingKeyObj = {
    'shortcut.previousSentence': 'left,a',
    'shortcut.nextSentence': 'right,d',
    'shortcut.repeatSentence': 'down,s',
    'shortcut.playPause': 'space,up,w',
    'shortcut.repeatSingleSentence': 'r',
    'shortcut.autoPause': 'u',
    'shortcut.toggleEnglishDisplay': 'e',
    'shortcut.toggleChineseDisplay': 'c',
    'shortcut.toggleWordLevelDisplay': 'l',
    'shortcut.toggleBilingualDisplay': 'b',
    'shortcut.nextTheme': 't',
    'shortcut.adjustBeginMinus': 'z',
    'shortcut.adjustBeginPlus': 'x',
    'shortcut.adjustEndMinus': 'n',
    'shortcut.adjustEndPlus': 'm',
    'shortcut.clearAdjust': 'v',
    'shortcut.nextPlaybackRate': 'p',
    'shortcut.aiChat': 'slash',
    'shortcut.addClip': 'shift+l',
    'shortcut.openControlPanel': 'shift+p',
    'userSelect.playbackRateStack':'',
    'apiKeys.youdao.secretId': '',
    'apiKeys.youdao.secretKey': '',
    'apiKeys.tencent.secretId': '',
    'apiKeys.tencent.secretKey': '',
    'apiKeys.openAi.key': '',
    'apiKeys.openAi.endpoint': '',
    'apiKeys.openAi.autoAppendV1': 'true',
    'apiKeys.openAi.stream': 'on',
    'translation.engine': 'tencent',
    'providers.subtitleTranslation': 'openai',
    'providers.dictionary': 'openai',
    'features.openai.enableSentenceLearning': 'true',
    'features.openai.subtitleTranslationMode': 'zh',
    'features.openai.subtitleCustomStyle': '',
    'models.openai.available': 'gpt-5.4-nano',
    'models.openai.sentenceLearning': 'gpt-5.4-nano',
    'models.openai.subtitleTranslation': 'gpt-5.4-nano',
    'models.openai.dictionary': 'gpt-5.4-nano',
    'models.local.active': LOCAL_AI_DEFAULT_MODEL_ID,
    // 本地模型 GPU 加速开关（Vulkan 平台生效）；默认开启，显卡/驱动不支持时由用户显式关闭。
    'models.local.gpu': 'true',
    'subtitleTranslation.engine': 'openai',
    'dictionary.engine': 'openai',
    // Service function enablement
    'services.openai.enableSentenceLearning': 'true',
    'services.openai.subtitleTranslationMode': 'zh',
    'appearance.theme': 'light',
    'appearance.fontSize': 'fontSizeLarge',
    'i18n.language': 'system',
    'player.autoPlayNext': 'false',
    'storage.path': '',
    'storage.collection': 'default',
    'proxy.mode': 'system',
    'proxy.url': '',
    'proxy.bypass_rules': '',
}
export type SettingKey = keyof typeof SettingKeyObj;
