export const SettingKeyObj = {
    'shortcut.previousSentence': 'left,a',
    'shortcut.nextSentence': 'right,d',
    'shortcut.repeatSentence': 'down,s',
    'shortcut.playPause': 'space,up,w',
    'shortcut.repeatSingleSentence': 'r',
    'shortcut.autoPause': 'u',
    'shortcut.toggleEnglishDisplay': 'e',
    'shortcut.toggleChineseDisplay': 'c',
    'shortcut.toggleWordLevelDisplay': 'l',
    'shortcut.toggleBilingualDisplay': 'b',
    'shortcut.nextTheme': 't',
    'shortcut.adjustBeginMinus': 'z',
    'shortcut.adjustBeginPlus': 'x',
    'shortcut.adjustEndMinus': 'n',
    'shortcut.adjustEndPlus': 'm',
    'shortcut.clearAdjust': 'v',
    'shortcut.nextPlaybackRate': 'p',
    'shortcut.aiChat': 'slash',
    'shortcut.toggleCopyMode': 'shift+y',
    'shortcut.addClip': 'shift+l',
    'shortcut.openControlPanel': 'shift+p',
    'userSelect.playbackRateStack':'',
    'apiKeys.youdao.secretId': '',
    'apiKeys.youdao.secretKey': '',
    'apiKeys.tencent.secretId': '',
    'apiKeys.tencent.secretKey': '',
    'apiKeys.openAi.key': '',
    'apiKeys.openAi.endpoint': '',
    'apiKeys.openAi.stream': 'on',
    'translation.engine': 'tencent',
    'model.gpt.default': 'gpt-4o-mini',
    // Service function enablement
    'services.openai.enableSentenceLearning': 'true',
    'services.openai.enableSubtitleTranslation': 'true',
    'services.openai.enableDictionary': 'true',
    'services.tencent.enableSubtitleTranslation': 'false',
    'services.youdao.enableDictionary': 'false',
    'appearance.theme': 'light',
    'appearance.fontSize': 'fontSizeLarge',
    'storage.path': '',
    'storage.collection': 'default',
}
export type SettingKey = keyof typeof SettingKeyObj;
