import { Container } from 'inversify';
import TYPES from './types';
import FavoriteClipsController from '@/backend/controllers/FavoriteClipsController';
import Controller from '@/backend/controllers/Controller';
import TagService, { TagServiceImpl } from '@/backend/services/TagService';
import TagController from '@/backend/controllers/TagController';
import SrtTimeAdjustService, { SrtTimeAdjustServiceImpl } from '@/backend/services/SrtTimeAdjustService';
import SubtitleService, { SubtitleServiceImpl } from '@/backend/services/SubtitleService';
import {
    SubtitleVocabularyAnalysisService,
    SubtitleVocabularyAnalysisServiceImpl,
} from '@/backend/services/SubtitleVocabularyAnalysisService';
import SrtTimeAdjustController from '@/backend/controllers/SrtTimeAdjustController';
import AiFuncController from '@/backend/controllers/AiFuncController';
import ChatStreamController from '@/backend/controllers/ChatStreamController';
import AiTransController from '@/backend/controllers/AiTransController';
import ConvertController from '@/backend/controllers/ConvertController';
import DpTaskController from '@/backend/controllers/DpTaskController';
import MediaController from '@/backend/controllers/MediaController';
import StorageController from '@/backend/controllers/StorageController';
import SystemController from '@/backend/controllers/SystemController';
import SubtitleController from '@/backend/controllers/SubtitleController';
import AiFuncService, { AiFuncServiceImpl } from '@/backend/services/AiFuncService';
import MainWindowRegistry from '@/backend/infrastructure/system/MainWindowRegistry';
import MainWindowRegistryImpl from '@/backend/infrastructure/system/MainWindowRegistryImpl';
import SystemConfigService, { SystemConfigServiceImpl } from '@/backend/services/SystemConfigService';
import SettingService, { SettingServiceImpl } from '@/backend/services/SettingService';
import { FavouriteClipsService, FavouriteClipsServiceImpl } from '@/backend/services/FavouriteClipsService';
import CacheService, { CacheServiceImpl } from '@/backend/services/CacheService';
import { ClipOssService } from '@/backend/services/OssService';
import ClipOssServiceImpl from '@/backend/infrastructure/storage/ClipOssServiceImpl';
import VideoLearningOssServiceImpl from '@/backend/infrastructure/storage/VideoLearningOssServiceImpl';
import { VideoLearningService, VideoLearningServiceImpl } from '@/backend/services/VideoLearningService';
import VideoLearningApiController from '@/backend/controllers/VideoLearningApiController';
import FfmpegService, { FfmpegServiceImpl } from '@/backend/services/FfmpegService';
import DpTaskService, { DpTaskServiceImpl } from '@/backend/services/DpTaskService';
import ChatService, { ChatServiceImpl } from '@/backend/services/ChatService';
import ChatSessionService, { ChatSessionServiceImpl } from '@/backend/services/ChatSessionService';
import ChatSessionStore, { InMemoryChatSessionStore } from '@/backend/services/chat/ChatSessionStore';
import AiProviderService, { AiProviderServiceImpl } from '@/backend/services/AiProviderService';
import ModelRoutingService, { ModelRoutingServiceImpl } from '@/backend/services/ModelRoutingService';
import ConvertService, { ConvertServiceImpl } from '@/backend/services/ConvertService';
import SplitVideoService, { SplitVideoServiceImpl } from '@/backend/services/SplitVideoService';
import MediaService, { MediaServiceImpl } from '@/backend/services/MediaService';
import ClientProviderService from '@/backend/services/ClientProviderService';
import YouDaoProvider from '@/backend/infrastructure/translate/providers/YouDaoProvider';
import TencentProvider from '@/backend/infrastructure/translate/providers/TencentProvider';
import TranslateService, { TranslateServiceImpl } from '@/backend/services/TranslateService';
import SubtitleTranslationService, {
    SubtitleTranslationServiceImpl,
} from '@/backend/services/subtitle-translation/SubtitleTranslationService';
import { YouDaoDictionaryClient } from '@/backend/services/gateways/translate/YouDaoDictionaryClient';
import { TencentTranslateClient } from '@/backend/services/gateways/translate/TencentTranslateClient';
import OpenAiSubtitleTranslationGateway from '@/backend/services/gateways/translate/OpenAiSubtitleTranslationGateway';
import OpenAiSubtitleTranslationGatewayImpl from '@/backend/infrastructure/translate/OpenAiSubtitleTranslationGatewayImpl';
import ConfigStoreFactoryImpl from '@/backend/infrastructure/config/ConfigStoreFactoryImpl';
import { ConfigStoreFactory } from '@/backend/services/gateways/ConfigStore';
import { SettingsStore } from '@/backend/services/gateways/SettingsStore';
import SettingsStoreImpl from '@/backend/infrastructure/settings/SettingsStoreImpl';
import WatchHistoryService, { WatchHistoryServiceImpl } from '@/backend/services/WatchHistoryService';
import WatchHistoryController from '@/backend/controllers/WatchHistoryController';
import SettingsController from '@/backend/controllers/SettingsController';
import { ParakeetModelController } from '@/backend/controllers/ParakeetModelController';
import ParakeetModelService, { ParakeetModelServiceImpl } from '@/backend/services/ParakeetModelService';
import { OpenAiService, OpenAIServiceImpl } from '@/backend/services/OpenAiService';
import { LocalTranscriptionServiceImpl, TranscriptionService } from '@/backend/services/TranscriptionService';
import { SherpaOnnxCli } from '@/backend/infrastructure/media/sherpa/SherpaOnnxCli';
import SpeechRecognitionGateway from '@/backend/services/gateways/media/SpeechRecognitionGateway';
import SherpaOnnxGatewayImpl from '@/backend/infrastructure/media/sherpa/SherpaOnnxGatewayImpl';
import { SherpaOnnxTtsCli } from '@/backend/infrastructure/media/sherpa/SherpaOnnxTtsCli';
import SherpaTtsModelService, { SherpaTtsModelServiceImpl } from '@/backend/services/SherpaTtsModelService';
import LocalTtsService, { LocalTtsServiceImpl } from '@/backend/services/LocalTtsService';
import { SherpaTtsModelController } from '@/backend/controllers/SherpaTtsModelController';
import { WordMatchService, WordMatchServiceImpl } from '@/backend/services/WordMatchService';
import VocabularyController from '@/backend/controllers/VocabularyController';
import VocabularyService, { VocabularyServiceImpl } from '@/backend/services/VocabularyService';
import RendererGateway from '@/backend/services/gateways/renderer/RendererGateway';
import RendererGatewayImpl from '@/backend/infrastructure/renderer/RendererGatewayImpl';
import RendererEvents from '@/backend/services/gateways/renderer/RendererEvents';
import RendererEventsImpl from '@/backend/infrastructure/renderer/RendererEventsImpl';
import WindowPort from '@/backend/services/gateways/window/WindowPort';
import WindowPortImpl from '@/backend/infrastructure/window/WindowPortImpl';
import FfmpegGateway from '@/backend/services/gateways/media/FfmpegGateway';
import FfmpegGatewayImpl from '@/backend/infrastructure/media/ffmpeg/FfmpegGatewayImpl';
import WordsRepository from '@/backend/services/repositories/WordsRepository';
import WordsRepositoryImpl from '@/backend/infrastructure/db/repositories/WordsRepositoryImpl';
import DpTaskRepository from '@/backend/services/repositories/DpTaskRepository';
import DpTaskRepositoryImpl from '@/backend/infrastructure/db/repositories/DpTaskRepositoryImpl';
import TranscriptionTaskRepository from '@/backend/services/repositories/TranscriptionTaskRepository';
import TranscriptionTaskRepositoryImpl from '@/backend/infrastructure/db/repositories/TranscriptionTaskRepositoryImpl';
import VideoLearningClipRepository from '@/backend/services/repositories/VideoLearningClipRepository';
import VideoLearningClipRepositoryImpl from '@/backend/infrastructure/db/repositories/VideoLearningClipRepositoryImpl';
import VideoLearningClipWordRepository from '@/backend/services/repositories/VideoLearningClipWordRepository';
import VideoLearningClipWordRepositoryImpl from '@/backend/infrastructure/db/repositories/VideoLearningClipWordRepositoryImpl';
import WatchHistoryRepository from '@/backend/services/repositories/WatchHistoryRepository';
import WatchHistoryRepositoryImpl from '@/backend/infrastructure/db/repositories/WatchHistoryRepositoryImpl';
import WatchHistoryExtRepository from '@/backend/services/repositories/WatchHistoryExtRepository';
import WatchHistoryExtRepositoryImpl from '@/backend/infrastructure/db/repositories/WatchHistoryExtRepositoryImpl';
import FavouriteClipsRepository from '@/backend/services/repositories/FavouriteClipsRepository';
import FavouriteClipsRepositoryImpl from '@/backend/infrastructure/db/repositories/FavouriteClipsRepositoryImpl';
import WordTranslatesRepository from '@/backend/services/repositories/WordTranslatesRepository';
import WordTranslatesRepositoryImpl from '@/backend/infrastructure/db/repositories/WordTranslatesRepositoryImpl';
import SentenceTranslatesRepository from '@/backend/services/repositories/SentenceTranslatesRepository';
import SentenceTranslatesRepositoryImpl from '@/backend/infrastructure/db/repositories/SentenceTranslatesRepositoryImpl';
import SysConfRepository from '@/backend/services/repositories/SysConfRepository';
import SysConfRepositoryImpl from '@/backend/infrastructure/db/repositories/SysConfRepositoryImpl';
import SubtitleTimestampAdjustmentsRepository from '@/backend/services/repositories/SubtitleTimestampAdjustmentsRepository';
import SubtitleTimestampAdjustmentsRepositoryImpl from '@/backend/infrastructure/db/repositories/SubtitleTimestampAdjustmentsRepositoryImpl';
import StorageDirectoryProvider from '@/backend/services/gateways/storage/StorageDirectoryProvider';
import StorageDirectoryProviderImpl from '@/backend/infrastructure/storage/StorageDirectoryProviderImpl';
import FileSystemGateway from '@/backend/services/gateways/storage/FileSystemGateway';
import FileSystemGatewayImpl from '@/backend/infrastructure/storage/FileSystemGatewayImpl';
import AccessRecoveringFileSystemGateway from '@/backend/infrastructure/storage/AccessRecoveringFileSystemGateway';
import db from '@/backend/infrastructure/db';
import type { Db } from '@/backend/infrastructure/db/createDb';


const container = new Container();
// 数据库单例：仓储层统一从这里注入，测试可用内存库替换。
container.bind<Db>(TYPES.Database).toConstantValue(db);
// Clients
container.bind<ClientProviderService<YouDaoDictionaryClient>>(TYPES.YouDaoClientProvider).to(YouDaoProvider).inSingletonScope();
container.bind<ClientProviderService<TencentTranslateClient>>(TYPES.TencentClientProvider).to(TencentProvider).inSingletonScope();
container.bind<ConfigStoreFactory>(TYPES.ConfigStoreFactory).to(ConfigStoreFactoryImpl).inSingletonScope();
container.bind<SettingsStore>(TYPES.SettingsStore).to(SettingsStoreImpl).inSingletonScope();
container.bind<ModelRoutingService>(TYPES.ModelRoutingService).to(ModelRoutingServiceImpl).inSingletonScope();
container.bind<AiProviderService>(TYPES.AiProviderService).to(AiProviderServiceImpl).inSingletonScope();
container.bind<OpenAiSubtitleTranslationGateway>(TYPES.OpenAiSubtitleTranslationGateway)
    .to(OpenAiSubtitleTranslationGatewayImpl)
    .inSingletonScope();
// Controllers
container.bind<Controller>(TYPES.Controller).to(FavoriteClipsController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(TagController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SrtTimeAdjustController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(AiFuncController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(ChatStreamController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(AiTransController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(ConvertController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(DpTaskController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(MediaController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(StorageController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SystemController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SubtitleController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(WatchHistoryController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SettingsController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(ParakeetModelController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SherpaTtsModelController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(VocabularyController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(VideoLearningApiController).inSingletonScope();
// Services
container.bind<RendererGateway>(TYPES.RendererGateway).to(RendererGatewayImpl).inSingletonScope();
container.bind<RendererEvents>(TYPES.RendererEvents).to(RendererEventsImpl).inSingletonScope();
container.bind<MainWindowRegistry>(TYPES.MainWindowRegistry).to(MainWindowRegistryImpl).inSingletonScope();
container.bind<WindowPort>(TYPES.WindowPort).to(WindowPortImpl).inSingletonScope();
container.bind<AiFuncService>(TYPES.AiFuncService).to(AiFuncServiceImpl).inSingletonScope();
container.bind<ParakeetModelService>(TYPES.ParakeetModelService).to(ParakeetModelServiceImpl).inSingletonScope();
container.bind<SherpaOnnxCli>(TYPES.SherpaOnnxCli).to(SherpaOnnxCli).inSingletonScope();
container.bind<SpeechRecognitionGateway>(TYPES.SpeechRecognitionGateway).to(SherpaOnnxGatewayImpl).inSingletonScope();
container.bind<SherpaOnnxTtsCli>(TYPES.SherpaOnnxTtsCli).to(SherpaOnnxTtsCli).inSingletonScope();
container.bind<SherpaTtsModelService>(TYPES.SherpaTtsModelService).to(SherpaTtsModelServiceImpl).inSingletonScope();
container.bind<LocalTtsService>(TYPES.LocalTtsService).to(LocalTtsServiceImpl).inSingletonScope();
container.bind<WordsRepository>(TYPES.WordsRepository).to(WordsRepositoryImpl).inSingletonScope();
container.bind<DpTaskRepository>(TYPES.DpTaskRepository).to(DpTaskRepositoryImpl).inSingletonScope();
container.bind<TranscriptionTaskRepository>(TYPES.TranscriptionTaskRepository).to(TranscriptionTaskRepositoryImpl).inSingletonScope();
container.bind<VideoLearningClipRepository>(TYPES.VideoLearningClipRepository).to(VideoLearningClipRepositoryImpl).inSingletonScope();
container.bind<VideoLearningClipWordRepository>(TYPES.VideoLearningClipWordRepository).to(VideoLearningClipWordRepositoryImpl).inSingletonScope();
container.bind<WatchHistoryRepository>(TYPES.WatchHistoryRepository).to(WatchHistoryRepositoryImpl).inSingletonScope();
container.bind<WatchHistoryExtRepository>(TYPES.WatchHistoryExtRepository).to(WatchHistoryExtRepositoryImpl).inSingletonScope();
container.bind<FavouriteClipsRepository>(TYPES.FavouriteClipsRepository).to(FavouriteClipsRepositoryImpl).inSingletonScope();
container.bind<WordTranslatesRepository>(TYPES.WordTranslatesRepository).to(WordTranslatesRepositoryImpl).inSingletonScope();
container.bind<SentenceTranslatesRepository>(TYPES.SentenceTranslatesRepository).to(SentenceTranslatesRepositoryImpl).inSingletonScope();
container.bind<SysConfRepository>(TYPES.SysConfRepository).to(SysConfRepositoryImpl).inSingletonScope();
container.bind<SubtitleTimestampAdjustmentsRepository>(TYPES.SubtitleTimestampAdjustmentsRepository).to(SubtitleTimestampAdjustmentsRepositoryImpl).inSingletonScope();
container.bind<ClipOssService>(TYPES.ClipOssService).to(ClipOssServiceImpl).inSingletonScope();
container.bind<ClipOssService>(TYPES.VideoLearningOssService).to(VideoLearningOssServiceImpl).inSingletonScope();
container.bind<FavouriteClipsService>(TYPES.FavouriteClips).to(FavouriteClipsServiceImpl).inSingletonScope();
container.bind<VideoLearningService>(TYPES.VideoLearningService).to(VideoLearningServiceImpl).inSingletonScope();
container.bind<TagService>(TYPES.TagService).to(TagServiceImpl).inSingletonScope();
container.bind<SrtTimeAdjustService>(TYPES.SrtTimeAdjustService).to(SrtTimeAdjustServiceImpl).inSingletonScope();
container.bind<SubtitleService>(TYPES.SubtitleService).to(SubtitleServiceImpl).inSingletonScope();
container.bind<SubtitleVocabularyAnalysisService>(TYPES.SubtitleVocabularyAnalysisService)
    .to(SubtitleVocabularyAnalysisServiceImpl)
    .inSingletonScope();
container.bind<SystemConfigService>(TYPES.SystemConfigService).to(SystemConfigServiceImpl).inSingletonScope();
container.bind<CacheService>(TYPES.CacheService).to(CacheServiceImpl).inSingletonScope();
container.bind<SettingService>(TYPES.SettingService).to(SettingServiceImpl).inSingletonScope();
container.bind<StorageDirectoryProvider>(TYPES.StorageDirectoryProvider).to(StorageDirectoryProviderImpl).inSingletonScope();
// 裸文件系统网关只做真实 IO；对外绑定的网关在其外层自动恢复外部路径的访问权限。
container.bind<FileSystemGateway>(TYPES.RawFileSystemGateway).to(FileSystemGatewayImpl).inSingletonScope();
container.bind<FileSystemGateway>(TYPES.FileSystemGateway).to(AccessRecoveringFileSystemGateway).inSingletonScope();
container.bind<FfmpegGateway>(TYPES.FfmpegGateway).to(FfmpegGatewayImpl).inSingletonScope();
container.bind<FfmpegService>(TYPES.FfmpegService).to(FfmpegServiceImpl).inSingletonScope();
container.bind<DpTaskService>(TYPES.DpTaskService).to(DpTaskServiceImpl).inSingletonScope();
container.bind<ChatService>(TYPES.ChatService).to(ChatServiceImpl).inSingletonScope();
container.bind<ChatSessionStore>(TYPES.ChatSessionStore).to(InMemoryChatSessionStore).inSingletonScope();
container.bind<ChatSessionService>(TYPES.ChatSessionService).to(ChatSessionServiceImpl).inSingletonScope();
container.bind<ConvertService>(TYPES.ConvertService).to(ConvertServiceImpl).inSingletonScope();
container.bind<SplitVideoService>(TYPES.SplitVideoService).to(SplitVideoServiceImpl).inSingletonScope();
container.bind<MediaService>(TYPES.MediaService).to(MediaServiceImpl).inSingletonScope();
container.bind<TranslateService>(TYPES.TranslateService).to(TranslateServiceImpl).inSingletonScope();
container.bind<SubtitleTranslationService>(TYPES.SubtitleTranslationService)
    .to(SubtitleTranslationServiceImpl)
    .inSingletonScope();
container.bind<WatchHistoryService>(TYPES.WatchHistoryService).to(WatchHistoryServiceImpl).inSingletonScope();
container.bind<OpenAiService>(TYPES.OpenAiService).to(OpenAIServiceImpl).inSingletonScope();
container.bind<TranscriptionService>(TYPES.LocalTranscriptionService).to(LocalTranscriptionServiceImpl).inSingletonScope();
container.bind<WordMatchService>(TYPES.WordMatchService).to(WordMatchServiceImpl).inSingletonScope();
container.bind<VocabularyService>(TYPES.VocabularyService).to(VocabularyServiceImpl).inSingletonScope();
export default container;
