import { Container } from 'inversify';
import TYPES from './types';
import FavoriteClipsController from '@/backend/controllers/FavoriteClipsController';
import Controller from '@/backend/interfaces/controller';
import TagService from '@/backend/services/TagService';
import TagController from '@/backend/controllers/TagController';
import SrtTimeAdjustService from '@/backend/services/SrtTimeAdjustService';
import { SubtitleServiceImpl } from '@/backend/services/impl/SubtitleServiceImpl';
import SubtitleService from '@/backend/services/SubtitleService';
import SrtTimeAdjustServiceImpl from '@/backend/services/impl/SrtTimeAdjustServiceImpl';
import SrtTimeAdjustController from '@/backend/controllers/SrtTimeAdjustController';
import AiFuncController from '@/backend/controllers/AiFuncController';
import AiTransController from '@/backend/controllers/AiTransController';
import ConvertController from '@/backend/controllers/ConvertController';
import DpTaskController from '@/backend/controllers/DpTaskController';
import MediaController from '@/backend/controllers/MediaController';
import StorageController from '@/backend/controllers/StorageController';
import SystemController from '@/backend/controllers/SystemController';
import SubtitleController from '@/backend/controllers/SubtitleController';
import SystemServiceImpl from '@/backend/services/impl/SystemServiceImpl';
import SystemService from '@/backend/services/SystemService';
import SystemConfigService from '@/backend/services/SystemConfigService';
import SystemConfigServiceImpl from '@/backend/services/impl/SystemConfigServiceImpl';
import { CacheServiceImpl } from '@/backend/services/impl/CacheService';
import SettingService from '@/backend/services/SettingService';
import SettingServiceImpl from '@/backend/services/impl/SettingServiceImpl';
import { FavouriteClipsService } from '@/backend/services/FavouriteClipsService';
import FavouriteClipsServiceImpl from '@/backend/services/impl/FavouriteClipsServiceImpl';
import CacheService from '@/backend/services/CacheService';
import { ClipOssService } from '@/backend/services/OssService';
import ClipOssServiceImpl from '@/backend/services/impl/ClipOssServiceImpl';
import VideoLearningOssServiceImpl from '@/backend/services/impl/VideoLearningOssServiceImpl';
import { VideoLearningService } from '@/backend/services/VideoLearningService';
import VideoLearningServiceImpl from '@/backend/services/impl/VideoLearningServiceImpl';
import VideoLearningApiController from '@/backend/controllers/VideoLearningApiController';
import LocationServiceImpl from '@/backend/services/impl/LocationServiceImpl';
import LocationService from '@/backend/services/LocationService';
import FfmpegService from '@/backend/services/FfmpegService';
import FfmpegServiceImpl from '@/backend/services/impl/FfmpegServiceImpl';
import DpTaskService from '@/backend/services/DpTaskService';
import DpTaskServiceImpl from '@/backend/services/impl/DpTaskServiceImpl';
import ChatService from '@/backend/services/ChatService';
import ChatServiceImpl from '@/backend/services/impl/ChatServiceImpl';
import AiProviderServiceImpl from '@/backend/services/impl/clients/AiProviderServiceImpl';
import AiServiceImpl, { AiService } from '@/backend/services/AiServiceImpl';
import WhisperService from '@/backend/services/WhisperService';
import WhisperServiceImpl from '@/backend/services/impl/WhisperServiceImpl';
import ConvertService from '@/backend/services/ConvertService';
import ConvertServiceImpl from '@/backend/services/impl/ConvertServiceImpl';
import SplitVideoService from '@/backend/services/SplitVideoService';
import SplitVideoServiceImpl from '@/backend/services/impl/SplitVideoServiceImpl';
import MediaService from '@/backend/services/MediaService';
import MediaServiceImpl from '@/backend/services/impl/MediaServiceImpl';
import ClientProviderService from '@/backend/services/ClientProviderService';
import YouDaoProvider from '@/backend/services/impl/clients/YouDaoProvider';
import TencentProvider from '@/backend/services/impl/clients/TencentProvider';
import TranslateServiceImpl from '@/backend/services/impl/TranslateServiceImpl';
import TranslateService from '@/backend/services/AiTransServiceImpl';
import TagServiceImpl from '@/backend/services/impl/TagServiceImpl';
import YouDaoClient from '@/backend/objs/YouDaoClient';
import TencentClient from '@/backend/objs/TencentClient';
import WatchHistoryService from '@/backend/services/WatchHistoryService';
import WatchHistoryServiceImpl from '@/backend/services/impl/WatchHistoryServiceImpl';
import WatchHistoryController from '@/backend/controllers/WatchHistoryController';
import SettingsController from '@/backend/controllers/SettingsController';
import { WhisperModelController } from '@/backend/controllers/WhisperModelController';
import { OpenAIServiceImpl } from '@/backend/services/impl/OpenAIServiceImpl';
import { OpenAiService } from '@/backend/services/OpenAiService';
import AiProviderService from '@/backend/services/AiProviderService';
import { TranscriptionService } from '@/backend/services/TranscriptionService';
import { CloudTranscriptionServiceImpl } from '@/backend/services/impl/CloudTranscriptionServiceImpl';
import { LocalTranscriptionServiceImpl } from '@/backend/services/impl/LocalTranscriptionServiceImpl';
import {WordMatchService} from '@/backend/services/WordMatchService';
import WordMatchServiceImpl from '@/backend/services/impl/WordMatchServiceImpl';
import VocabularyController from '@/backend/controllers/VocabularyController';
import VocabularyService from '@/backend/services/VocabularyService';
import VocabularyServiceImpl from '@/backend/services/impl/VocabularyServiceImpl';
import RendererGateway from '@/backend/services/RendererGateway';
import RendererGatewayImpl from '@/backend/services/impl/RendererGatewayImpl';
import RendererEvents from '@/backend/services/RendererEvents';
import RendererEventsImpl from '@/backend/services/impl/RendererEventsImpl';
import WordsRepository from '@/backend/infrastructure/db/repositories/WordsRepository';
import WordsRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/WordsRepositoryImpl';
import DpTaskRepository from '@/backend/infrastructure/db/repositories/DpTaskRepository';
import DpTaskRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/DpTaskRepositoryImpl';
import VideoLearningClipRepository from '@/backend/infrastructure/db/repositories/VideoLearningClipRepository';
import VideoLearningClipRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/VideoLearningClipRepositoryImpl';
import VideoLearningClipWordRepository from '@/backend/infrastructure/db/repositories/VideoLearningClipWordRepository';
import VideoLearningClipWordRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/VideoLearningClipWordRepositoryImpl';
import WatchHistoryRepository from '@/backend/infrastructure/db/repositories/WatchHistoryRepository';
import WatchHistoryRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/WatchHistoryRepositoryImpl';
import FavouriteClipsRepository from '@/backend/infrastructure/db/repositories/FavouriteClipsRepository';
import FavouriteClipsRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/FavouriteClipsRepositoryImpl';
import WordTranslatesRepository from '@/backend/infrastructure/db/repositories/WordTranslatesRepository';
import WordTranslatesRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/WordTranslatesRepositoryImpl';
import SentenceTranslatesRepository from '@/backend/infrastructure/db/repositories/SentenceTranslatesRepository';
import SentenceTranslatesRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/SentenceTranslatesRepositoryImpl';
import SysConfRepository from '@/backend/infrastructure/db/repositories/SysConfRepository';
import SysConfRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/SysConfRepositoryImpl';
import SubtitleTimestampAdjustmentsRepository from '@/backend/infrastructure/db/repositories/SubtitleTimestampAdjustmentsRepository';
import SubtitleTimestampAdjustmentsRepositoryImpl from '@/backend/infrastructure/db/repositories/impl/SubtitleTimestampAdjustmentsRepositoryImpl';


const container = new Container();
// Clients
container.bind<ClientProviderService<YouDaoClient>>(TYPES.YouDaoClientProvider).to(YouDaoProvider).inSingletonScope();
container.bind<ClientProviderService<TencentClient>>(TYPES.TencentClientProvider).to(TencentProvider).inSingletonScope();
container.bind<AiProviderService>(TYPES.AiProviderService).to(AiProviderServiceImpl).inSingletonScope();
// Controllers
container.bind<Controller>(TYPES.Controller).to(FavoriteClipsController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(TagController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SrtTimeAdjustController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(AiFuncController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(AiTransController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(ConvertController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(DpTaskController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(MediaController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(StorageController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SystemController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SubtitleController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(WatchHistoryController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SettingsController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(WhisperModelController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(VocabularyController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(VideoLearningApiController).inSingletonScope();
// Services
container.bind<RendererGateway>(TYPES.RendererGateway).to(RendererGatewayImpl).inSingletonScope();
container.bind<RendererEvents>(TYPES.RendererEvents).to(RendererEventsImpl).inSingletonScope();
container.bind<WordsRepository>(TYPES.WordsRepository).to(WordsRepositoryImpl).inSingletonScope();
container.bind<DpTaskRepository>(TYPES.DpTaskRepository).to(DpTaskRepositoryImpl).inSingletonScope();
container.bind<VideoLearningClipRepository>(TYPES.VideoLearningClipRepository).to(VideoLearningClipRepositoryImpl).inSingletonScope();
container.bind<VideoLearningClipWordRepository>(TYPES.VideoLearningClipWordRepository).to(VideoLearningClipWordRepositoryImpl).inSingletonScope();
container.bind<WatchHistoryRepository>(TYPES.WatchHistoryRepository).to(WatchHistoryRepositoryImpl).inSingletonScope();
container.bind<FavouriteClipsRepository>(TYPES.FavouriteClipsRepository).to(FavouriteClipsRepositoryImpl).inSingletonScope();
container.bind<WordTranslatesRepository>(TYPES.WordTranslatesRepository).to(WordTranslatesRepositoryImpl).inSingletonScope();
container.bind<SentenceTranslatesRepository>(TYPES.SentenceTranslatesRepository).to(SentenceTranslatesRepositoryImpl).inSingletonScope();
container.bind<SysConfRepository>(TYPES.SysConfRepository).to(SysConfRepositoryImpl).inSingletonScope();
container.bind<SubtitleTimestampAdjustmentsRepository>(TYPES.SubtitleTimestampAdjustmentsRepository).to(SubtitleTimestampAdjustmentsRepositoryImpl).inSingletonScope();
container.bind<ClipOssService>(TYPES.ClipOssService).to(ClipOssServiceImpl).inSingletonScope();
container.bind<ClipOssService>(TYPES.VideoLearningOssService).to(VideoLearningOssServiceImpl).inSingletonScope();
container.bind<FavouriteClipsService>(TYPES.FavouriteClips).to(FavouriteClipsServiceImpl).inSingletonScope();
container.bind<VideoLearningService>(TYPES.VideoLearningService).to(VideoLearningServiceImpl).inSingletonScope();
container.bind<TagService>(TYPES.TagService).to(TagServiceImpl).inSingletonScope();
container.bind<SrtTimeAdjustService>(TYPES.SrtTimeAdjustService).to(SrtTimeAdjustServiceImpl).inSingletonScope();
container.bind<SubtitleService>(TYPES.SubtitleService).to(SubtitleServiceImpl).inSingletonScope();
container.bind<SystemService>(TYPES.SystemService).to(SystemServiceImpl).inSingletonScope();
container.bind<SystemConfigService>(TYPES.SystemConfigService).to(SystemConfigServiceImpl).inSingletonScope();
container.bind<CacheService>(TYPES.CacheService).to(CacheServiceImpl).inSingletonScope();
container.bind<SettingService>(TYPES.SettingService).to(SettingServiceImpl).inSingletonScope();
container.bind<LocationService>(TYPES.LocationService).to(LocationServiceImpl).inSingletonScope();
container.bind<FfmpegService>(TYPES.FfmpegService).to(FfmpegServiceImpl).inSingletonScope();
container.bind<DpTaskService>(TYPES.DpTaskService).to(DpTaskServiceImpl).inSingletonScope();
container.bind<ChatService>(TYPES.ChatService).to(ChatServiceImpl).inSingletonScope();
container.bind<AiService>(TYPES.AiService).to(AiServiceImpl).inSingletonScope();
container.bind<WhisperService>(TYPES.WhisperService).to(WhisperServiceImpl).inSingletonScope();
container.bind<ConvertService>(TYPES.ConvertService).to(ConvertServiceImpl).inSingletonScope();
container.bind<SplitVideoService>(TYPES.SplitVideoService).to(SplitVideoServiceImpl).inSingletonScope();
container.bind<MediaService>(TYPES.MediaService).to(MediaServiceImpl).inSingletonScope();
container.bind<TranslateService>(TYPES.TranslateService).to(TranslateServiceImpl).inSingletonScope();
container.bind<WatchHistoryService>(TYPES.WatchHistoryService).to(WatchHistoryServiceImpl).inSingletonScope();
container.bind<OpenAiService>(TYPES.OpenAiService).to(OpenAIServiceImpl).inSingletonScope();
container.bind<TranscriptionService>(TYPES.CloudTranscriptionService).to(CloudTranscriptionServiceImpl).inSingletonScope();
container.bind<TranscriptionService>(TYPES.LocalTranscriptionService).to(LocalTranscriptionServiceImpl).inSingletonScope();
container.bind<WordMatchService>(TYPES.WordMatchService).to(WordMatchServiceImpl).inSingletonScope();
container.bind<VocabularyService>(TYPES.VocabularyService).to(VocabularyServiceImpl).inSingletonScope();
export default container;
