import { Container } from 'inversify';
import TYPES from './types';
import FavoriteClipsController from '@/backend/adapters/controllers/FavoriteClipsController';
import Controller from '@/backend/adapters/controllers/Controller';
import TagService from '@/backend/application/services/TagService';
import TagController from '@/backend/adapters/controllers/TagController';
import SrtTimeAdjustService from '@/backend/application/services/SrtTimeAdjustService';
import { SubtitleServiceImpl } from '@/backend/application/services/impl/SubtitleServiceImpl';
import SubtitleService from '@/backend/application/services/SubtitleService';
import SrtTimeAdjustServiceImpl from '@/backend/application/services/impl/SrtTimeAdjustServiceImpl';
import SrtTimeAdjustController from '@/backend/adapters/controllers/SrtTimeAdjustController';
import AiFuncController from '@/backend/adapters/controllers/AiFuncController';
import AiTransController from '@/backend/adapters/controllers/AiTransController';
import ConvertController from '@/backend/adapters/controllers/ConvertController';
import DpTaskController from '@/backend/adapters/controllers/DpTaskController';
import MediaController from '@/backend/adapters/controllers/MediaController';
import StorageController from '@/backend/adapters/controllers/StorageController';
import SystemController from '@/backend/adapters/controllers/SystemController';
import SubtitleController from '@/backend/adapters/controllers/SubtitleController';
import AiFuncService from '@/backend/application/services/impl/AiFuncService';
import MainWindowRegistry from '@/backend/infrastructure/system/MainWindowRegistry';
import MainWindowRegistryImpl from '@/backend/infrastructure/system/MainWindowRegistryImpl';
import SystemConfigService from '@/backend/application/services/SystemConfigService';
import SystemConfigServiceImpl from '@/backend/application/services/impl/SystemConfigServiceImpl';
import { CacheServiceImpl } from '@/backend/application/services/impl/CacheService';
import SettingService from '@/backend/application/services/SettingService';
import SettingServiceImpl from '@/backend/application/services/impl/SettingServiceImpl';
import { FavouriteClipsService } from '@/backend/application/services/FavouriteClipsService';
import FavouriteClipsServiceImpl from '@/backend/application/services/impl/FavouriteClipsServiceImpl';
import CacheService from '@/backend/application/services/CacheService';
import { ClipOssService } from '@/backend/application/services/OssService';
import ClipOssServiceImpl from '@/backend/application/services/impl/ClipOssServiceImpl';
import VideoLearningOssServiceImpl from '@/backend/application/services/impl/VideoLearningOssServiceImpl';
import { VideoLearningService } from '@/backend/application/services/VideoLearningService';
import VideoLearningServiceImpl from '@/backend/application/services/impl/VideoLearningServiceImpl';
import VideoLearningApiController from '@/backend/adapters/controllers/VideoLearningApiController';
import LocationServiceImpl from '@/backend/application/services/impl/LocationServiceImpl';
import LocationService from '@/backend/application/services/LocationService';
import FfmpegService from '@/backend/application/services/FfmpegService';
import FfmpegServiceImpl from '@/backend/application/services/impl/FfmpegServiceImpl';
import DpTaskService from '@/backend/application/services/DpTaskService';
import DpTaskServiceImpl from '@/backend/application/services/impl/DpTaskServiceImpl';
import ChatService from '@/backend/application/services/ChatService';
import ChatServiceImpl from '@/backend/application/services/impl/ChatServiceImpl';
import AiProviderServiceImpl from '@/backend/application/services/impl/clients/AiProviderServiceImpl';
import AiServiceImpl, { AiService } from '@/backend/application/services/AiServiceImpl';
import WhisperService from '@/backend/application/services/WhisperService';
import WhisperServiceImpl from '@/backend/application/services/impl/WhisperServiceImpl';
import ConvertService from '@/backend/application/services/ConvertService';
import ConvertServiceImpl from '@/backend/application/services/impl/ConvertServiceImpl';
import SplitVideoService from '@/backend/application/services/SplitVideoService';
import SplitVideoServiceImpl from '@/backend/application/services/impl/SplitVideoServiceImpl';
import MediaService from '@/backend/application/services/MediaService';
import MediaServiceImpl from '@/backend/application/services/impl/MediaServiceImpl';
import ClientProviderService from '@/backend/application/services/ClientProviderService';
import YouDaoProvider from '@/backend/infrastructure/translate/providers/YouDaoProvider';
import TencentProvider from '@/backend/infrastructure/translate/providers/TencentProvider';
import TranslateServiceImpl from '@/backend/application/services/impl/TranslateServiceImpl';
import TranslateService from '@/backend/application/services/AiTransServiceImpl';
import TagServiceImpl from '@/backend/application/services/impl/TagServiceImpl';
import { YouDaoDictionaryClient } from '@/backend/application/ports/gateways/translate/YouDaoDictionaryClient';
import { TencentTranslateClient } from '@/backend/application/ports/gateways/translate/TencentTranslateClient';
import ConfigStoreFactoryImpl from '@/backend/infrastructure/config/ConfigStoreFactoryImpl';
import { ConfigStoreFactory } from '@/backend/application/ports/gateways/ConfigStore';
import { SettingsStore } from '@/backend/application/ports/gateways/SettingsStore';
import SettingsStoreImpl from '@/backend/infrastructure/settings/SettingsStoreImpl';
import SettingsKeyValueService from '@/backend/application/services/impl/SettingsKeyValueService';
import WatchHistoryService from '@/backend/application/services/WatchHistoryService';
import WatchHistoryServiceImpl from '@/backend/application/services/impl/WatchHistoryServiceImpl';
import WatchHistoryController from '@/backend/adapters/controllers/WatchHistoryController';
import SettingsController from '@/backend/adapters/controllers/SettingsController';
import { WhisperModelController } from '@/backend/adapters/controllers/WhisperModelController';
import { WhisperModelService } from '@/backend/application/services/impl/WhisperModelService';
import { OpenAIServiceImpl } from '@/backend/application/services/impl/OpenAIServiceImpl';
import { OpenAiService } from '@/backend/application/services/OpenAiService';
import { OpenAiWhisper } from '@/backend/application/ports/gateways/OpenAiWhisper';
import AiProviderService from '@/backend/application/services/AiProviderService';
import OpenAiWhisperGatewayImpl from '@/backend/infrastructure/openai/OpenAiWhisperGatewayImpl';
import { TranscriptionService } from '@/backend/application/services/TranscriptionService';
import { CloudTranscriptionServiceImpl } from '@/backend/application/services/impl/CloudTranscriptionServiceImpl';
import { LocalTranscriptionServiceImpl } from '@/backend/application/services/impl/LocalTranscriptionServiceImpl';
import {WhisperCppCli} from '@/backend/infrastructure/media/whisper/WhisperCppCli';
import {WordMatchService} from '@/backend/application/services/WordMatchService';
import WordMatchServiceImpl from '@/backend/application/services/impl/WordMatchServiceImpl';
import VocabularyController from '@/backend/adapters/controllers/VocabularyController';
import VocabularyService from '@/backend/application/services/VocabularyService';
import VocabularyServiceImpl from '@/backend/application/services/impl/VocabularyServiceImpl';
import RendererGateway from '@/backend/application/ports/gateways/renderer/RendererGateway';
import RendererGatewayImpl from '@/backend/infrastructure/renderer/RendererGatewayImpl';
import RendererEvents from '@/backend/application/ports/gateways/renderer/RendererEvents';
import RendererEventsImpl from '@/backend/infrastructure/renderer/RendererEventsImpl';
import WindowPort from '@/backend/application/ports/gateways/window/WindowPort';
import WindowPortImpl from '@/backend/infrastructure/window/WindowPortImpl';
import WordsRepository from '@/backend/application/ports/repositories/WordsRepository';
import WordsRepositoryImpl from '@/backend/infrastructure/db/repositories/WordsRepositoryImpl';
import DpTaskRepository from '@/backend/application/ports/repositories/DpTaskRepository';
import DpTaskRepositoryImpl from '@/backend/infrastructure/db/repositories/DpTaskRepositoryImpl';
import VideoLearningClipRepository from '@/backend/application/ports/repositories/VideoLearningClipRepository';
import VideoLearningClipRepositoryImpl from '@/backend/infrastructure/db/repositories/VideoLearningClipRepositoryImpl';
import VideoLearningClipWordRepository from '@/backend/application/ports/repositories/VideoLearningClipWordRepository';
import VideoLearningClipWordRepositoryImpl from '@/backend/infrastructure/db/repositories/VideoLearningClipWordRepositoryImpl';
import WatchHistoryRepository from '@/backend/application/ports/repositories/WatchHistoryRepository';
import WatchHistoryRepositoryImpl from '@/backend/infrastructure/db/repositories/WatchHistoryRepositoryImpl';
import FavouriteClipsRepository from '@/backend/application/ports/repositories/FavouriteClipsRepository';
import FavouriteClipsRepositoryImpl from '@/backend/infrastructure/db/repositories/FavouriteClipsRepositoryImpl';
import WordTranslatesRepository from '@/backend/application/ports/repositories/WordTranslatesRepository';
import WordTranslatesRepositoryImpl from '@/backend/infrastructure/db/repositories/WordTranslatesRepositoryImpl';
import SentenceTranslatesRepository from '@/backend/application/ports/repositories/SentenceTranslatesRepository';
import SentenceTranslatesRepositoryImpl from '@/backend/infrastructure/db/repositories/SentenceTranslatesRepositoryImpl';
import SysConfRepository from '@/backend/application/ports/repositories/SysConfRepository';
import SysConfRepositoryImpl from '@/backend/infrastructure/db/repositories/SysConfRepositoryImpl';
import SubtitleTimestampAdjustmentsRepository from '@/backend/application/ports/repositories/SubtitleTimestampAdjustmentsRepository';
import SubtitleTimestampAdjustmentsRepositoryImpl from '@/backend/infrastructure/db/repositories/SubtitleTimestampAdjustmentsRepositoryImpl';


const container = new Container();
// Clients
container.bind<ClientProviderService<YouDaoDictionaryClient>>(TYPES.YouDaoClientProvider).to(YouDaoProvider).inSingletonScope();
container.bind<ClientProviderService<TencentTranslateClient>>(TYPES.TencentClientProvider).to(TencentProvider).inSingletonScope();
container.bind<ConfigStoreFactory>(TYPES.ConfigStoreFactory).to(ConfigStoreFactoryImpl).inSingletonScope();
container.bind<SettingsStore>(TYPES.SettingsStore).to(SettingsStoreImpl).inSingletonScope();
container.bind<SettingsKeyValueService>(TYPES.SettingsKeyValueService).to(SettingsKeyValueService).inSingletonScope();
container.bind<AiProviderService>(TYPES.AiProviderService).to(AiProviderServiceImpl).inSingletonScope();
// Controllers
container.bind<Controller>(TYPES.Controller).to(FavoriteClipsController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(TagController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SrtTimeAdjustController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(AiFuncController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(AiTransController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(ConvertController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(DpTaskController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(MediaController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(StorageController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SystemController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SubtitleController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(WatchHistoryController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(SettingsController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(WhisperModelController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(VocabularyController).inSingletonScope();
container.bind<Controller>(TYPES.Controller).to(VideoLearningApiController).inSingletonScope();
// Services
container.bind<RendererGateway>(TYPES.RendererGateway).to(RendererGatewayImpl).inSingletonScope();
container.bind<RendererEvents>(TYPES.RendererEvents).to(RendererEventsImpl).inSingletonScope();
container.bind<MainWindowRegistry>(TYPES.MainWindowRegistry).to(MainWindowRegistryImpl).inSingletonScope();
container.bind<WindowPort>(TYPES.WindowPort).to(WindowPortImpl).inSingletonScope();
container.bind<AiFuncService>(TYPES.AiFuncService).to(AiFuncService).inSingletonScope();
container.bind<WhisperModelService>(TYPES.WhisperModelService).to(WhisperModelService).inSingletonScope();
container.bind<WhisperCppCli>(TYPES.WhisperCppCli).to(WhisperCppCli).inSingletonScope();
container.bind<WordsRepository>(TYPES.WordsRepository).to(WordsRepositoryImpl).inSingletonScope();
container.bind<DpTaskRepository>(TYPES.DpTaskRepository).to(DpTaskRepositoryImpl).inSingletonScope();
container.bind<VideoLearningClipRepository>(TYPES.VideoLearningClipRepository).to(VideoLearningClipRepositoryImpl).inSingletonScope();
container.bind<VideoLearningClipWordRepository>(TYPES.VideoLearningClipWordRepository).to(VideoLearningClipWordRepositoryImpl).inSingletonScope();
container.bind<WatchHistoryRepository>(TYPES.WatchHistoryRepository).to(WatchHistoryRepositoryImpl).inSingletonScope();
container.bind<FavouriteClipsRepository>(TYPES.FavouriteClipsRepository).to(FavouriteClipsRepositoryImpl).inSingletonScope();
container.bind<WordTranslatesRepository>(TYPES.WordTranslatesRepository).to(WordTranslatesRepositoryImpl).inSingletonScope();
container.bind<SentenceTranslatesRepository>(TYPES.SentenceTranslatesRepository).to(SentenceTranslatesRepositoryImpl).inSingletonScope();
container.bind<SysConfRepository>(TYPES.SysConfRepository).to(SysConfRepositoryImpl).inSingletonScope();
container.bind<SubtitleTimestampAdjustmentsRepository>(TYPES.SubtitleTimestampAdjustmentsRepository).to(SubtitleTimestampAdjustmentsRepositoryImpl).inSingletonScope();
container.bind<ClipOssService>(TYPES.ClipOssService).to(ClipOssServiceImpl).inSingletonScope();
container.bind<ClipOssService>(TYPES.VideoLearningOssService).to(VideoLearningOssServiceImpl).inSingletonScope();
container.bind<FavouriteClipsService>(TYPES.FavouriteClips).to(FavouriteClipsServiceImpl).inSingletonScope();
container.bind<VideoLearningService>(TYPES.VideoLearningService).to(VideoLearningServiceImpl).inSingletonScope();
container.bind<TagService>(TYPES.TagService).to(TagServiceImpl).inSingletonScope();
container.bind<SrtTimeAdjustService>(TYPES.SrtTimeAdjustService).to(SrtTimeAdjustServiceImpl).inSingletonScope();
container.bind<SubtitleService>(TYPES.SubtitleService).to(SubtitleServiceImpl).inSingletonScope();
container.bind<SystemConfigService>(TYPES.SystemConfigService).to(SystemConfigServiceImpl).inSingletonScope();
container.bind<CacheService>(TYPES.CacheService).to(CacheServiceImpl).inSingletonScope();
container.bind<SettingService>(TYPES.SettingService).to(SettingServiceImpl).inSingletonScope();
container.bind<LocationService>(TYPES.LocationService).to(LocationServiceImpl).inSingletonScope();
container.bind<FfmpegService>(TYPES.FfmpegService).to(FfmpegServiceImpl).inSingletonScope();
container.bind<DpTaskService>(TYPES.DpTaskService).to(DpTaskServiceImpl).inSingletonScope();
container.bind<ChatService>(TYPES.ChatService).to(ChatServiceImpl).inSingletonScope();
container.bind<AiService>(TYPES.AiService).to(AiServiceImpl).inSingletonScope();
container.bind<WhisperService>(TYPES.WhisperService).to(WhisperServiceImpl).inSingletonScope();
container.bind<ConvertService>(TYPES.ConvertService).to(ConvertServiceImpl).inSingletonScope();
container.bind<SplitVideoService>(TYPES.SplitVideoService).to(SplitVideoServiceImpl).inSingletonScope();
container.bind<MediaService>(TYPES.MediaService).to(MediaServiceImpl).inSingletonScope();
container.bind<TranslateService>(TYPES.TranslateService).to(TranslateServiceImpl).inSingletonScope();
container.bind<WatchHistoryService>(TYPES.WatchHistoryService).to(WatchHistoryServiceImpl).inSingletonScope();
container.bind<OpenAiService>(TYPES.OpenAiService).to(OpenAIServiceImpl).inSingletonScope();
container.bind<OpenAiWhisper>(TYPES.OpenAiWhisper).to(OpenAiWhisperGatewayImpl).inSingletonScope();
container.bind<TranscriptionService>(TYPES.CloudTranscriptionService).to(CloudTranscriptionServiceImpl).inSingletonScope();
container.bind<TranscriptionService>(TYPES.LocalTranscriptionService).to(LocalTranscriptionServiceImpl).inSingletonScope();
container.bind<WordMatchService>(TYPES.WordMatchService).to(WordMatchServiceImpl).inSingletonScope();
container.bind<VocabularyService>(TYPES.VocabularyService).to(VocabularyServiceImpl).inSingletonScope();
export default container;
