const TYPES = {
    ClipOssService: Symbol('ClipOssService'),
    FavouriteClips: Symbol('FavouriteClips'),
    Controller: Symbol('Controller'),
    WatchProject: Symbol('WatchProject'),
    DlVideo: Symbol('DlVideo'),
    TagService: Symbol('TagService'),
    SubtitleService: Symbol('SubtitleService'),
    SrtTimeAdjustService: Symbol('SubtitleTimestampAdjustmentService'),
    SystemService: Symbol('SystemService'),
    CacheService: Symbol('CacheService'),
    SettingService: Symbol('SettingService'),
    LocationService: Symbol('LocationService'),
    DpTaskService: Symbol('DpTaskService'),
    AiFuncService: Symbol('AiFuncService'),
    AiProviderService: Symbol('AiProviderService'),
    AiService: Symbol('AiService'),
    ChatService: Symbol('ChatService'),
    ChildProcessService: Symbol('ChildProcessService'),
    FfmpegService: Symbol('FfmpegService'),
    SplitVideoService: Symbol('SplitVideoService'),
    WhisperService: Symbol('WhisperService'),
    ConvertService: Symbol('ConvertService'),
    MediaService: Symbol('MediaService'),
};

export default TYPES;
