const TYPES = {
    ClipOssService: Symbol('ClipOssService'),
    VideoLearningOssService: Symbol('VideoLearningOssService'),
    FavouriteClips: Symbol('FavouriteClips'),
    VideoLearningService: Symbol('VideoLearningService'),
    Controller: Symbol('Controller'),
    WatchProject: Symbol('WatchProject'),
    TagService: Symbol('TagService'),
    SubtitleService: Symbol('SubtitleService'),
    SrtTimeAdjustService: Symbol('SubtitleTimestampAdjustmentService'),
    SystemService: Symbol('SystemService'),
    SystemConfigService: Symbol('SystemConfigService'),
    CacheService: Symbol('CacheService'),
    SettingService: Symbol('SettingService'),
    LocationService: Symbol('LocationService'),
    DpTaskService: Symbol('DpTaskService'),
    AiService: Symbol('AiService'),
    ChatService: Symbol('ChatService'),
    FfmpegService: Symbol('FfmpegService'),
    SplitVideoService: Symbol('SplitVideoService'),
    WhisperService: Symbol('WhisperService'),
    ConvertService: Symbol('ConvertService'),
    MediaService: Symbol('MediaService'),
    TranslateService: Symbol('TranslateService'),
    WatchHistoryService: Symbol('WatchHistoryService'),
    OpenAiService: Symbol('OpenAiService'),
    CloudTranscriptionService: Symbol('CloudTranscriptionService'),
    LocalTranscriptionService: Symbol('LocalTranscriptionService'),
    WordMatchService: Symbol('WordMatchService'),
    VocabularyService: Symbol('VocabularyService'),
    RendererGateway: Symbol('RendererGateway'),
    WordsRepository: Symbol('WordsRepository'),
    DpTaskRepository: Symbol('DpTaskRepository'),
    VideoLearningClipRepository: Symbol('VideoLearningClipRepository'),
    VideoLearningClipWordRepository: Symbol('VideoLearningClipWordRepository'),
    WatchHistoryRepository: Symbol('WatchHistoryRepository'),
    // Clients
    YouDaoClientProvider: Symbol('YouDaoClientProvider'),
    TencentClientProvider: Symbol('TencentClientProvider'),
    AiProviderService: Symbol('AiProviderService'),
};

export default TYPES;
